# Generated by Django 4.2.1 on 2023-05-16 12:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_thumbnail_alter_user_profile_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=150)),
                ('user_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email address')),
                ('address', models.CharField(max_length=300, verbose_name='Address')),
                ('telephone_number', models.CharField(max_length=20, verbose_name='Telephone')),
                ('total_amount', models.FloatField()),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('paid_status', models.BooleanField(default=False)),
                ('invoice', models.CharField(max_length=200)),
            ],
        ),
    ]
