# Generated by Django 4.2.1 on 2023-05-16 15:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_shipment_address_alter_shipment_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='total_amount',
            new_name='course_price',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='order_date',
        ),
        migrations.AddField(
            model_name='shipment',
            name='buy_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='paid_status',
            field=models.CharField(default='unpaid', max_length=20),
        ),
    ]
